# Generated by Django 4.2.30 on 2026-05-20 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import socis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognoms', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=socis.models.ruta_foto)),
                ('tipus', models.CharField(choices=[('DIMONIS', 'Dimonis'), ('BATUCADA', 'Batucada')], default='DIMONIS', max_length=10)),
                ('data_alta', models.DateField(auto_now_add=True)),
                ('actiu', models.BooleanField(default=True)),
                ('usuari', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soci', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soci',
                'verbose_name_plural': 'Socis',
                'ordering': ['cognoms', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSoci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('DNI', 'DNI / NIE'), ('ALTRE', 'Altre')], default='ALTRE', max_length=10)),
                ('nom', models.CharField(max_length=200)),
                ('fitxer', models.FileField(upload_to=socis.models.ruta_document)),
                ('data_pujada', models.DateTimeField(auto_now_add=True)),
                ('soci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='socis.soci')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-data_pujada'],
            },
        ),
        migrations.CreateModel(
            name='Pagament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 'Gener'), (2, 'Febrer'), (3, 'Març'), (4, 'Abril'), (5, 'Maig'), (6, 'Juny'), (7, 'Juliol'), (8, 'Agost'), (9, 'Setembre'), (10, 'Octubre'), (11, 'Novembre'), (12, 'Desembre')])),
                ('pagat', models.BooleanField(default=False)),
                ('data_pagament', models.DateField(blank=True, null=True)),
                ('soci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagaments', to='socis.soci')),
            ],
            options={
                'verbose_name': 'Pagament',
                'verbose_name_plural': 'Pagaments',
                'ordering': ['any', 'mes'],
                'unique_together': {('soci', 'any', 'mes')},
            },
        ),
    ]
