# Generated by Django 4.2.30 on 2026-05-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soci',
            options={'ordering': ['numero_soci', 'cognoms', 'nom'], 'verbose_name': 'Soci', 'verbose_name_plural': 'Socis'},
        ),
        migrations.AddField(
            model_name='soci',
            name='data_curs_pirotecnia',
            field=models.DateField(blank=True, null=True, verbose_name='Data curs CREE'),
        ),
        migrations.AddField(
            model_name='soci',
            name='data_naixement',
            field=models.DateField(blank=True, null=True, verbose_name='Data de naixement'),
        ),
        migrations.AddField(
            model_name='soci',
            name='data_proteccio_dades',
            field=models.DateField(blank=True, null=True, verbose_name='Data firma protecció dades'),
        ),
        migrations.AddField(
            model_name='soci',
            name='es_menor',
            field=models.BooleanField(default=False, verbose_name="És menor d'edat"),
        ),
        migrations.AddField(
            model_name='soci',
            name='numero_soci',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número de soci'),
        ),
        migrations.AddField(
            model_name='soci',
            name='permis_pare_signat',
            field=models.BooleanField(default=False, verbose_name='Permís pare/mare signat'),
        ),
        migrations.AddField(
            model_name='soci',
            name='proteccio_dades_firmada',
            field=models.BooleanField(default=False, verbose_name='Protecció de dades firmada'),
        ),
        migrations.AddField(
            model_name='soci',
            name='te_curs_pirotecnia',
            field=models.BooleanField(default=False, verbose_name='Curs pirotècnia (CREE)'),
        ),
        migrations.AddField(
            model_name='soci',
            name='tutor_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menors_tutelats', to='socis.soci', verbose_name="Tutor legal (major d'edat)"),
        ),
        migrations.AlterField(
            model_name='documentsoci',
            name='tipus',
            field=models.CharField(choices=[('DNI', 'DNI / NIE'), ('PERMIS_PARE', 'Permís pare/mare'), ('PROTECCIO', 'Protecció de dades'), ('CREE', 'Curs pirotècnia (CREE)'), ('ALTRE', 'Altre')], default='ALTRE', max_length=15),
        ),
        migrations.AlterField(
            model_name='soci',
            name='dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI / NIE'),
        ),
    ]
