# Generated by Django 4.2.30 on 2026-05-20 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socis', '0002_alter_soci_options_soci_data_curs_pirotecnia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsoci',
            options={'ordering': ['tipus', '-data_pujada'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='pagament',
            options={'ordering': ['any', 'mes'], 'verbose_name': 'Pagament mensual', 'verbose_name_plural': 'Pagaments mensuals'},
        ),
        migrations.AddField(
            model_name='pagament',
            name='import_pagat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='soci',
            name='data_caducitat_dni',
            field=models.DateField(blank=True, null=True, verbose_name='Caducitat DNI'),
        ),
        migrations.AlterField(
            model_name='documentsoci',
            name='tipus',
            field=models.CharField(choices=[('DNI', 'DNI / NIE'), ('PERMIS_PARE', 'Permís pare/mare'), ('PROTECCIO', 'Protecció de dades (LOPD)'), ('CREE', 'Curs pirotècnia (CREE)'), ('ALTRE', 'Altre')], default='ALTRE', max_length=15),
        ),
        migrations.AlterField(
            model_name='soci',
            name='data_proteccio_dades',
            field=models.DateField(blank=True, null=True, verbose_name='Data firma LOPD'),
        ),
        migrations.AlterField(
            model_name='soci',
            name='tutor_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menors_tutelats', to='socis.soci', verbose_name='Tutor legal'),
        ),
        migrations.CreateModel(
            name='PagamentMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any', models.IntegerField()),
                ('pagat', models.BooleanField(default=False)),
                ('data_pagament', models.DateField(blank=True, null=True)),
                ('import_pagat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('soci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricules', to='socis.soci')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrícules',
                'ordering': ['-any'],
                'unique_together': {('soci', 'any')},
            },
        ),
    ]
