# Generated by Django 4.2.30 on 2026-05-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socis', '0003_alter_documentsoci_options_alter_pagament_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagament',
            options={'ordering': ['any', 'mes'], 'verbose_name': 'Mensualitat', 'verbose_name_plural': 'Mensualitats'},
        ),
        migrations.AlterModelOptions(
            name='pagamentmatricula',
            options={'verbose_name': "Matrícula d'entrada", 'verbose_name_plural': "Matrícules d'entrada"},
        ),
        migrations.AlterUniqueTogether(
            name='pagamentmatricula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='soci',
            name='adreca',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adreça'),
        ),
        migrations.AddField(
            model_name='soci',
            name='ciutat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Municipi'),
        ),
        migrations.AddField(
            model_name='soci',
            name='codi_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Codi postal'),
        ),
        migrations.AddField(
            model_name='soci',
            name='data_baixa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de baixa'),
        ),
        migrations.AlterField(
            model_name='pagamentmatricula',
            name='soci',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='socis.soci'),
        ),
        migrations.AlterField(
            model_name='soci',
            name='data_alta',
            field=models.DateField(blank=True, null=True, verbose_name="Data d'alta"),
        ),
        migrations.CreateModel(
            name='PagamentQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any', models.IntegerField()),
                ('pagat', models.BooleanField(default=False)),
                ('data_pagament', models.DateField(blank=True, null=True)),
                ('import_pagat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('soci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='socis.soci')),
            ],
            options={
                'verbose_name': 'Quota anual',
                'verbose_name_plural': 'Quotes anuals',
                'ordering': ['-any'],
                'unique_together': {('soci', 'any')},
            },
        ),
    ]
