# Generated by Django 4.2.30 on 2026-05-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socis', '0004_alter_pagament_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrecJunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrec', models.CharField(choices=[('PRESIDENT', 'President/a'), ('VICEPRESIDENT', 'Vicepresident/a'), ('SECRETARI', 'Secretari/a'), ('TRESORER', 'Tresorer/a'), ('VOCAL', 'Vocal'), ('ALTRE', 'Altre càrrec')], max_length=20)),
                ('funcions', models.TextField(blank=True, verbose_name='Funcions i responsabilitats')),
                ('ordre', models.PositiveIntegerField(default=99, verbose_name='Ordre de visualització')),
                ('data_inici', models.DateField(blank=True, null=True, verbose_name="Data d'inici del càrrec")),
                ('soci', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrec_junta', to='socis.soci')),
            ],
            options={
                'verbose_name': 'Càrrec de Junta',
                'verbose_name_plural': 'Càrrecs de Junta',
                'ordering': ['ordre', 'carrec'],
            },
        ),
    ]
