# Generated by Django 4.2.30 on 2026-05-20 21:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('categoria', models.CharField(choices=[('MATERIAL', 'Material'), ('TRANSPORT', 'Transport'), ('ASSEGURANCES', 'Assegurances'), ('LOCAL', 'Local / Lloger'), ('ACTIVITATS', 'Activitats'), ('ADMINISTRATIU', 'Administratiu'), ('ALTRE', 'Altre')], default='ALTRE', max_length=20)),
                ('descripcio', models.CharField(max_length=300)),
                ('proveidor', models.CharField(blank=True, max_length=200)),
                ('import_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura_adjunta', models.FileField(blank=True, null=True, upload_to='despeses/factures/')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despeses',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipus', models.CharField(choices=[('FACTURA', 'Factura'), ('PRESSUPOST', 'Pressupost')], default='FACTURA', max_length=15)),
                ('client', models.CharField(max_length=200)),
                ('adreca_client', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('estat', models.CharField(choices=[('PENDENT', 'Pendent'), ('PAGAT', 'Pagat'), ('CANCELAT', 'Cancel·lat')], default='PENDENT', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Factures',
                'ordering': ['-data', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(max_length=300)),
                ('quantitat', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='facturacio.factura')),
            ],
            options={
                'verbose_name': 'Línia de factura',
                'verbose_name_plural': 'Línies de factura',
            },
        ),
    ]
