# Generated by Django 4.2.30 on 2026-05-20 22:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF / CIF')),
                ('adreca', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('descripcio', models.CharField(blank=True, max_length=400)),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producte / Servei',
                'verbose_name_plural': 'Productes / Serveis',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='nif_client',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIF / CIF client'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='client',
            field=models.CharField(max_length=200, verbose_name='Nom client'),
        ),
        migrations.AddField(
            model_name='factura',
            name='client_registrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='facturacio.client', verbose_name='Client (registrat)'),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='producte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linies_factura', to='facturacio.producte'),
        ),
    ]
