# Generated by Django 4.2.30 on 2026-05-21 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacio', '0002_client_producte_factura_nif_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='factura_adjunta',
        ),
        migrations.AddField(
            model_name='despesa',
            name='amb_targeta_colla',
            field=models.BooleanField(default=False, verbose_name='Pagat amb targeta de la colla'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='estat',
            field=models.CharField(choices=[('PENDENT', 'Pendent de revisar'), ('REVISAT', 'Revisat')], default='PENDENT', max_length=10),
        ),
        migrations.AddField(
            model_name='despesa',
            name='partida',
            field=models.CharField(blank=True, choices=[('COLLA', 'Colla'), ('DIMONIS', 'Dimonis'), ('BATUCADA', 'Batucada')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='despesa',
            name='soci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despeses', to=settings.AUTH_USER_MODEL, verbose_name='Soci'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='despeses/tickets/', verbose_name='Ticket / factura'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(blank=True, choices=[('MATERIAL', 'Material'), ('TRANSPORT', 'Transport'), ('ASSEGURANCES', 'Assegurances'), ('LOCAL', 'Local / Lloger'), ('ACTIVITATS', 'Activitats'), ('ADMINISTRATIU', 'Administratiu'), ('ALTRE', 'Altre')], default='', max_length=20),
        ),
    ]
