# Generated by Django 4.2.30 on 2026-05-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacio', '0003_despesa_partida_soci_estat_targeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='concepte',
            field=models.CharField(blank=True, max_length=400, verbose_name='Concepte / referència'),
        ),
        migrations.AddField(
            model_name='factura',
            name='exempt_iva',
            field=models.BooleanField(default=False, verbose_name="Exempt d'IVA (art. 20.1.14è LIVA)"),
        ),
        migrations.AddField(
            model_name='factura',
            name='forma_pagament',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferència bancària'), ('EFECTIU', 'Efectiu'), ('TARGETA', 'Targeta')], default='TRANSFERENCIA', max_length=15, verbose_name='Forma de pagament'),
        ),
    ]
