# Generated by Django 4.2.30 on 2026-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacio', '0004_factura_forma_pagament_exempt_iva_concepte'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='partida',
            field=models.CharField(blank=True, choices=[('COLLA', 'Colla'), ('DIMONIS', 'Dimonis'), ('BATUCADA', 'Batucada')], default='', max_length=10, verbose_name='Partida'),
        ),
    ]
