# Generated by Django 4.2.30 on 2026-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacio', '0005_factura_partida'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProveidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveidor', models.CharField(max_length=200, verbose_name='Proveïdor')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Núm. factura proveïdor')),
                ('data', models.DateField(verbose_name='Data factura')),
                ('data_venciment', models.DateField(blank=True, null=True, verbose_name='Data venciment')),
                ('descripcio', models.CharField(max_length=400, verbose_name='Concepte')),
                ('import_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Import total (€)')),
                ('iva_inclou', models.BooleanField(default=True, verbose_name='Import inclou IVA')),
                ('partida', models.CharField(blank=True, choices=[('COLLA', 'Colla'), ('DIMONIS', 'Dimonis'), ('BATUCADA', 'Batucada')], default='', max_length=10, verbose_name='Partida')),
                ('estat', models.CharField(choices=[('PENDENT', 'Pendent de pagar'), ('PAGADA', 'Pagada')], default='PENDENT', max_length=10)),
                ('fitxer', models.FileField(blank=True, null=True, upload_to='factures_proveidor/', verbose_name='Fitxer (PDF/imatge)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Factura de proveïdor',
                'verbose_name_plural': 'Factures de proveïdors',
                'ordering': ['-data'],
            },
        ),
    ]
