# Generated by Django 4.2.30 on 2026-05-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_colla', models.CharField(default='Espiadimonis de Felanitx', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracio/')),
                ('email_contacte', models.EmailField(blank=True, max_length=254)),
                ('telefon_contacte', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Configuració',
                'verbose_name_plural': 'Configuració',
            },
        ),
    ]
