# Generated by Django 4.2.30 on 2026-05-20 22:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_configuracio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracio',
            name='matricula',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=8, verbose_name='Matrícula anual (tots els socis)'),
        ),
        migrations.AddField(
            model_name='configuracio',
            name='mensualitat_batucada',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, verbose_name='Mensualitat Batucada'),
        ),
    ]
