# Generated by Django 4.2.30 on 2026-05-20 22:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_configuracio_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracio',
            name='quota_anual',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8, verbose_name='Quota anual (tots els socis)'),
        ),
        migrations.AlterField(
            model_name='configuracio',
            name='matricula',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8, verbose_name="Matrícula (1r any d'alta, un sol cop)"),
        ),
        migrations.AlterField(
            model_name='configuracio',
            name='mensualitat_batucada',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=8, verbose_name='Mensualitat Batucada'),
        ),
    ]
