# Generated by Django 4.2.30 on 2026-05-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_configuracio_quota_anual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('COLLA', 'Reunió de Colla'), ('JUNTA', 'Reunió de Junta')], default='COLLA', max_length=10)),
                ('titol', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('fitxer', models.FileField(blank=True, null=True, upload_to='actes/')),
                ('publicat', models.BooleanField(default=True)),
                ('data_pujada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actes',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='configuracio',
            name='adreca',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adreça'),
        ),
        migrations.AddField(
            model_name='configuracio',
            name='cif',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIF / NIF'),
        ),
        migrations.AddField(
            model_name='configuracio',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN bancari'),
        ),
    ]
